### ISSUE TITLE
直接运行会报错

### ISSUE THREAD

**Issue by guolaopi** [iacker/iacker-ui#1]
![图片](https://user-images.githubusercontent.com/11360515/119286621-62d21f80-bc77-11eb-9b29-febb098579b6.png)
直接运行会报错，原因是package.json中项目版本格式有误，建议修改。
![图片](https://user-images.githubusercontent.com/11360515/119286537-2f8f9080-bc77-11eb-8a22-12b9a9065a0e.png)

**Comment by dcbanop** [comment]
已修改
